// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQCWWhpQiH_KMBetqA9wqK4rZM21UB5_I',
    appId: '1:173160679469:web:f4a02e45080dae78c650a4',
    messagingSenderId: '173160679469',
    projectId: 'kidoo-c83a4',
    authDomain: 'kidoo-c83a4.firebaseapp.com',
    storageBucket: 'kidoo-c83a4.firebasestorage.app',
    measurementId: 'G-WDHEZTMZKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0RYYCYU40RPz4UZJHaTiaLxFXAyh_nWI',
    appId: '1:173160679469:android:1290cc9b027cb2dbc650a4',
    messagingSenderId: '173160679469',
    projectId: 'kidoo-c83a4',
    storageBucket: 'kidoo-c83a4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQCWWhpQiH_KMBetqA9wqK4rZM21UB5_I',
    appId: '1:173160679469:web:418010d4aa6708f3c650a4',
    messagingSenderId: '173160679469',
    projectId: 'kidoo-c83a4',
    authDomain: 'kidoo-c83a4.firebaseapp.com',
    storageBucket: 'kidoo-c83a4.firebasestorage.app',
    measurementId: 'G-REX1GZT2K6',
  );

}